Make code Python3 compatible and perform cosmetic changes
danielmurray/adaptiv pull request #2
Opened 2017-02-06 14:40 UTC by Vages

The step counting parts of your repo could turn out to be very useful for my master’s thesis. Therefore I have taken the time to make it Python3 compatible, as well as making some aesthetic changes (PEP-8, deleting unused imports and variables).

2017-02-06 16:40 UTC, danielmurray commented
LGTM, can you point out specifically which parts of the code are not Python3 compatible, just for my knowledge.

2017-02-06 16:41 UTC, Vages commented
@danielmurray Will do!

2017-02-06 16:45 UTC, Vages reviewed
The only Python3-incompatible place (except for all print statement-to-function updates).

2017-02-06 16:45 UTC, Vages commented on sensorData/result.py
> -	for test, sub_tests in tests.iteritems():
Not Python3-compatible

2017-02-06 16:45 UTC, Vages commented on sensorData/result.py
> +    for test, sub_tests in iter(tests.items()):
Updated to be Python3 (and 2) compatible as per http://legacy.python.org/dev/peps/pep-0469/

2017-02-06 23:19 UTC, danielmurray requested changes

2017-02-06 23:19 UTC, danielmurray commented on .gitignore
> +
Why are these files in your root project folder?

2017-02-08 11:41 UTC, Vages commented on .gitignore
> +
Are you thinking of the lines I have added? Those are taken from Github’s official Python .gitignore (https://github.com/github/gitignore/blob/master/Python.gitignore) and Jetbrains .gitignore files (https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore).

2017-02-11 18:10 UTC, danielmurray commented on .gitignore
> +
I'm alright with the python standard .gitignore, but let's take out the Jetbrains .gitignores

2017-02-13 12:31 UTC, Vages commented on .gitignore
> +
That should do it.

2017-02-13 16:47 UTC, danielmurray commented
LGTM

2017-02-13 16:47 UTC, merged